### ISSUE TITLE
Readme: Clarify what's in the config file

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/vegacapsule#198] opened 2022-07-20 14:57 UTC
It’s not clear what parameters are available in the configuration(the config.hcl file).

**Comment by gordsport** [comment] 2022-07-21 09:39
Can we make it more obvious as to what each of the config files give us?

- whoever created the configs, can we get a summary of what these are?
- document these

**Comment by gordsport** [comment] 2022-11-01 14:43
Closing as a duplicate of: 
- https://github.com/vegaprotocol/vegacapsule/issues/9

**Closed by gordsport** 2022-11-01 14:43 UTC
Labels: documentation, vegacapsule
